baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'VeryCute.com.au - Rabbit specific boarding based in the InnerWest of Sydney'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Designed by <a class="Kaushik" href="https://www.kaushik.com.au/">Kaushik</a>'

seo:
  meta_og_title: "VeryCute.com.au"
  meta_og_type: "website"
  meta_og_url: "https://verycute.com.au"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "We are a Rabbit specific boarding based in the InnerWest of Sydney"
  meta_twitter_card: "summary"
  meta_twitter_site: "@_Kaushik"
  meta_twitter_creator: "@_Kaushik"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
